# Generated by Django 2.0.5 on 2018-06-04 05:06

import Finance.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=3, max_digits=1000000)),
                ('owner', models.ForeignKey(on_delete=models.SET(Finance.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockPurchaseHisotry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=10)),
                ('time_purchased', models.DateTimeField(auto_now_add=True)),
                ('amout_purchased', models.DecimalField(decimal_places=3, max_digits=1000000)),
                ('hm_purchased', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.Finance')),
            ],
        ),
        migrations.CreateModel(
            name='StockSoldHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=10)),
                ('time_sold', models.DateTimeField(auto_now_add=True)),
                ('amout_sold', models.DecimalField(decimal_places=3, max_digits=1000000)),
                ('hm_sold', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.Finance')),
            ],
        ),
    ]
