# Generated by Django 2.0.5 on 2018-05-29 10:44

import Finance.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=models.SET(Finance.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
