# Generated by Django 2.0.5 on 2018-05-29 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_finance_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPurchaseHisotry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=10)),
                ('time_purchased', models.DateTimeField(auto_now_add=True)),
                ('amout_purchased', models.DecimalField(decimal_places=3, max_digits=1000000)),
                ('hm_purchased', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StockSoldHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=10)),
                ('time_sold', models.DateTimeField(auto_now_add=True)),
                ('amout_sold', models.DecimalField(decimal_places=3, max_digits=1000000)),
                ('hm_sold', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='finance',
            name='crypto_coin',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='stock_ticker',
        ),
        migrations.AddField(
            model_name='finance',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocksoldhistory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.Finance'),
        ),
        migrations.AddField(
            model_name='stockpurchasehisotry',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.Finance'),
        ),
    ]
