# Generated by Django 2.0.5 on 2018-05-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='profile_image',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='uploads/%Y/%m/%d/', width_field=100),
        ),
    ]
