# Generated by Django 2.0.5 on 2018-05-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_userprofilemodel_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
