# Generated by Django 2.0.5 on 2018-05-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20180529_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
