# Generated by Django 2.0.5 on 2018-05-29 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20180529_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='profile_image',
        ),
    ]
