# Generated by Django 2.0.5 on 2018-06-04 05:03

import Lesson.models
import Lesson.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(max_length=120, unique=True)),
                ('chapter_quote', models.CharField(blank=True, max_length=200, null=True)),
                ('chapter_quote_author', models.CharField(blank=True, max_length=100, null=True)),
                ('chapter_introduction', models.TextField(help_text='Write your Introduction here.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=50, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('abstract', models.CharField(blank=True, max_length=200, null=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=100, validators=[Lesson.validators.validate_subject])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('owner', models.ForeignKey(on_delete=models.SET(Lesson.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lesson.LessonPlan'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=models.SET(Lesson.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
