# Generated by Django 2.0.5 on 2018-05-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonplan',
            old_name='lesson_content',
            new_name='content',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='subject',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
