# Generated by Django 2.0.5 on 2018-05-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0002_auto_20180528_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='subject',
            field=models.CharField(default='physics', max_length=100),
        ),
    ]
