# Generated by Django 2.0.5 on 2018-05-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0003_auto_20180528_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='content',
            field=models.TextField(max_length=300),
        ),
    ]
