# Generated by Django 2.0.5 on 2018-06-04 05:09

import Lesson.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Lesson', '0004_auto_20180604_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(max_length=120, unique=True)),
                ('chapter_quote', models.CharField(blank=True, max_length=200, null=True)),
                ('chapter_quote_author', models.CharField(blank=True, max_length=100, null=True)),
                ('chapter_introduction', models.TextField(help_text='Write your Introduction here.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lesson.LessonPlan')),
                ('owner', models.ForeignKey(default=1, on_delete=models.SET(Lesson.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
