# Generated by Django 2.0.5 on 2018-05-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0004_auto_20180528_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='content',
            field=models.TextField(),
        ),
    ]
