# Generated by Django 2.0.5 on 2018-05-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0005_auto_20180528_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='lesson_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
