# Generated by Django 2.0.5 on 2018-05-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0007_lessonplan_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
