# Generated by Django 2.0.5 on 2018-05-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0009_lessonplan_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
