# Generated by Django 2.0.5 on 2018-05-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0010_lessonplan_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
