# Generated by Django 2.0.5 on 2018-05-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0013_lessonplan_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
