# Generated by Django 2.0.5 on 2018-05-29 07:49

import Lesson.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0014_auto_20180529_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='subject',
            field=models.CharField(max_length=100, validators=[Lesson.validators.validate_subject]),
        ),
    ]
