# Generated by Django 2.0.5 on 2018-05-29 08:04

import Lesson.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Lesson', '0015_auto_20180529_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=models.SET(Lesson.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
