# Generated by Django 2.0.5 on 2018-05-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0016_lessonplan_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='content',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='content',
            field=models.ManyToManyField(blank=True, null=True, to='Lesson.Section'),
        ),
    ]
