# Generated by Django 2.0.5 on 2018-05-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0017_auto_20180529_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='chapter',
            field=models.ManyToManyField(blank=True, null=True, to='Lesson.Section'),
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='content',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
