# Generated by Django 2.0.5 on 2018-05-29 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0018_auto_20180529_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(max_length=120)),
                ('chapter_content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='chapter',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.AddField(
            model_name='chapter',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lesson.LessonPlan'),
        ),
    ]
