# Generated by Django 2.0.5 on 2018-05-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0019_auto_20180529_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='content',
        ),
        migrations.AddField(
            model_name='chapter',
            name='chpater_introduction',
            field=models.TextField(default='def'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='abstract',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='lesson_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
