# Generated by Django 2.0.5 on 2018-05-29 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0021_auto_20180529_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=120)),
                ('section_content', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter_content',
            new_name='chapter_introduction',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='chpater_introduction',
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_quote',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_quote_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lesson.Chapter'),
        ),
    ]
